# Board configuration for the environment

boards:
  num_boards: 3

  marker_size: 0.087
  marker_spacing: 0.017
  border_bits: 1

  output_height: 800
  output_width: 800

  board_0:
    rows: 2
    cols: 2
    ids: [31, 32, 33, 34]

  board_1:
    rows: 2
    cols: 3
    ids: [25,26,27,28,29,30]

  board_2:
    rows: 4
    cols: 4
    ids: []
