# Board configuration for the environment

num_boards: 3

marker_size: 0.05
marker_spacing: 0.01
border_bits: 1

output_height: 800
output_width: 800

board_0:
  rows: 2
  cols: 2
  ids: [1, 10, 20, 30]

board_1:
  rows: 1
  cols: 1
  ids: [5]

board_2:
  rows: 4
  cols: 4
  ids: []
