# Common configuration for Breadcrumb guidance system

# System Settings
system:
#  adaptive_thresh_win_size_min: 3
#  adaptive_thresh_win_size_max: 23
#  adaptive_thresh_win_size_step: 10
#  adaptive_thresh_constant: 7
#  min_marker_perimeter_rate: 0.03
#  max_marker_perimeter_rate: 4.0
#  polygonal_approx_accuracy_rate: 0.05
#  min_corner_distance_rate: 10.0
#  min_distance_to_border: 3
#  min_marker_distance_rate: 0.05
  do_corner_refinement: true
#  corner_refinement_win_size: 11
#  corner_refinement_max_iterations: 30
#  corner_refinement_min_accuracy: 0.1
#  marker_border_bits: 1
#  perspective_remove_pixel_per_cell: 8
#  perspective_remove_ignored_margin_per_cell: 0.13
#  max_erroneous_bits_in_border_rate: 0.04
#  min_otsu_std_dev: 5.0
#  error_correction_rate: 0.6
